# Generated by Django 6.0.7 on 2026-07-26 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="ai_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="case",
            name="ai_status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="patient_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["ai_status"], name="cases_case_ai_stat_9d7191_idx"
            ),
        ),
    ]
