# Generated by Django 6.0.7 on 2026-08-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_case_ai_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseimage",
            name="ai_attention_map",
            field=models.ImageField(blank=True, null=True, upload_to="attention_maps/"),
        ),
        migrations.AddField(
            model_name="caseimage",
            name="ai_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caseimage",
            name="ai_prediction",
            field=models.CharField(
                blank=True,
                choices=[("benign", "Benign"), ("malignant", "Malignant")],
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="caseimage",
            name="ai_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
